EnterpriseApp.BackOffice/Controllers/RestaurantConfigController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EnterpriseApp.API.Core.Services;
using EnterpriseApp.API.Core.Services.Interface;
using EnterpriseApp.API.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EnterpriseApp.BackOffice.Controllers
{
    public class RestaurantConfigController : BackOfficeBaseController
    {
        public RestaurantConfigController(IRestaurantService restaurantService, IUserService userService, IFileService fileService, IOptions<AppSettings> appSetting) : base(restaurantService, userService, fileService, appSetting)
        {
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            if (TempData.ContainsKey("Result"))
            {
                ViewBag.Result = TempData["Result"].ToString();
            }
            else if (TempData.ContainsKey("InvalidResult"))
            {
                ViewBag.InvalidResult = TempData["InvalidResult"].ToString();
            }

            return View();
        }

        public IActionResult CheckResturantStatus(int postalCode)
        {
            var result = _restaurantService.CheckResturantStatus(postalCode);

            return new JsonResult(new { status = result, isSuccess = true});
        }

        public IActionResult SetResturantStatus(int postalCode, bool status)
        {
            var result = _restaurantService.ChangeResturantStatus(postalCode, status);

            if(result)
                TempData["Result"] = "Status updated successfully";
            else if(!result)
                TempData["InvalidResult"] = "Invalid postal code";

            return new JsonResult(new { isSuccess = true });
        }
    }
}

EnterpriseApp.BackOffice/Controllers/RestaurantController.cs
using EnterpriseApp.API.Core.Exceptions;
using EnterpriseApp.API.Core.Services;
using EnterpriseApp.API.Core.Services.Interface;
using EnterpriseApp.API.Models;
using EnterpriseApp.API.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace EnterpriseApp.BackOffice.Controllers
{
    public class RestaurantController : BackOfficeBaseController
    {
        public RestaurantController(IRestaurantService restaurantService, IUserService userService, IFileService fileService, IOptions<AppSettings> appSetting) : base(restaurantService, userService, fileService, appSetting)
        {
        }

        #region Public

        public IActionResult ViewRestaurants()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetAllRestaurants()
        {
            //Get form data from client side
            var requestFormData = Request.Form;
            string search = requestFormData["search[value]"];
            string draw = requestFormData["draw"];
            string order = requestFormData["order[0][column]"];
            string orderDir = requestFormData["order[0][dir]"];
            int startRec = Convert.ToInt32(requestFormData["start"]);
            int pageSize = Convert.ToInt32(requestFormData["length"]);

            var pagingParam = new PagingQueryParam
            {
                StartingIndex = startRec,
                PageSize = pageSize,
                Filter = search,
                Sort = $"{order}|{orderDir}" //Column|Order
            };

            var restaurants = _restaurantService.GetAllRestaurants(pagingParam);

            dynamic response = new
            {
                Data = restaurants.List,
                Draw = draw,
                RecordsFiltered = restaurants.TotalRecords,
                RecordsTotal = restaurants.TotalRecords
            };

            return Ok(response);
        }

        public IActionResult CreateRestaurant()
        {
            RestaurantRequest request = new RestaurantRequest()
            {
                Country = GetCountry(),
                Days = GetDays(),
                MapIcons = GetSubcategories(),
                Category = GetCategories(),
                BadgesModel = GetBadges(),
                SubcategoriesList = GetSubcategories(),
            };

            if (TempData.ContainsKey("Result"))
            {
                ViewBag.Result = TempData["Result"].ToString();
            }

            return View(request);
        }

        [HttpPost]
        public IActionResult CreateRestaurant([FromBody]RestaurantRequest request)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = _restaurantService.AddRestaurant(request);

                    if (result.IsSuccessful)
                    {
                        TempData["Result"] = "Restaurant successfully Created";
                        return new JsonResult(new { isSuccess = result.IsSuccessful });
                    }
                }
                catch (ApplicationLogicException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    return View(request);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "This action cannot be performed");
                    return View(request);
                }
            }

            return View(request);
        }

        public IActionResult RestaurantDetails(int id)
        {
            var restaurant = _restaurantService.GetBackOfficeRestaurantById(id);

            RestaurantModel request = new RestaurantModel()
            {
                Id = restaurant.Id,
                RName = restaurant.RName,
                RStreet = restaurant.RStreet,
                RCity = restaurant.RCity,
                RContact = restaurant.RContact,
                RLongitude = restaurant.RLongitude,
                RLatitude = restaurant.RLatitude,
                GooglePlaceId = restaurant.GooglePlaceId,
                RAddress = restaurant.RAddress,
                RDescription = restaurant.RDescription,
                OpeningHours = restaurant.OpeningHours,
                CountryName = restaurant.CountryName,
                RMetro = restaurant.RMetro,
                IsOpen = restaurant.IsOpen,
                RPostalCode = restaurant.RPostalCode,
                RPrice = restaurant.RPrice,
                RPriceDes = restaurant.RPriceDes,
                RRecommendation = restaurant.RRecommendation,
                CategoryName = restaurant.CategoryName,
                SubcategoriesList = restaurant.SubcategoriesList,
                ResBadges = restaurant.ResBadges,
                Session2 = restaurant.Session2,
                Session1 = restaurant.Session1
            };

            return View(request);
        }

        [HttpGet]
        public IActionResult EditRestaurant(int id)
        {
            var restaurant = _restaurantService.GetBackOfficeRestaurantById(id);

            RestaurantUpdateRequest request = new RestaurantUpdateRequest()
            {
                RestaurantId = restaurant.Id,
                RName = restaurant.RName,
                RStreet = restaurant.RStreet,
                RCity = restaurant.RCity,
                RContact = restaurant.RContact,
                RLongitude = restaurant.RLongitude,
                RLatitude = restaurant.RLatitude,
                GooglePlaceId = restaurant.GooglePlaceId,
                RAddress = restaurant.RAddress,
                RDescription = restaurant.RDescription,
                RPostalCode = restaurant.RPostalCode,
                ImagesList = restaurant.Images,
                RRecommendation = restaurant.RRecommendation,
                RMetro = restaurant.RMetro,
                MapIcon = restaurant.MapIcon,
                RPrice = restaurant.RPrice,
                RPriceDes = restaurant.RPriceDes,
                Countries = GetCountry(),
                Days = GetDays(),
                MapIcons = GetSubcategories(),
                Category = GetCategories(),
                OpeningHours = restaurant.OpeningHours,
                OpeningHoursList = restaurant.OpeningHoursList,
                CountryId = restaurant.CountryId,
                CategoryId = restaurant.CategoryId,
                SubcategoriesList = restaurant.SubcategoriesList,
                ResBadges = restaurant.ResBadges,
                Session1 = restaurant.Session1,
                Session2 = restaurant.Session2
            };

            if (TempData.ContainsKey("Result"))
            {
                ViewBag.Result = TempData["Result"].ToString();
            }

            return View(request);
        }

        [HttpPost]
        public IActionResult EditRestaurant([FromBody]RestaurantUpdateRequest request)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var result = _restaurantService.EditRestaurant(request);

                    if (result.IsSuccessful)
                    {
                        TempData["Result"] = "Restaurant successfully Updated";
                        return new JsonResult(new { isSuccess = result.IsSuccessful });
                    }
                }
                catch (ApplicationLogicException ex)
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                    return View(request);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError(string.Empty, "This action cannot be performed");
                    return View(request);
                }
            }

            return View(request);
        }

        public IActionResult DeleteRestaurant(int id)
        {
            try
            {
                var result = _restaurantService.DeleteRestaurent(id);

                if (result.IsSuccessful)
                {
                    TempData["Result"] = "Restaurant successfully deleted";
                    return new JsonResult(new { isSuccess = result.IsSuccessful });
                }
                else
                    return View();
            }
            catch (ApplicationLogicException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View();
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "This action cannot be performed");
                return View();
            }
        }

        [Route("DeleteResFile/{id:int}")]
        public IActionResult DeleteResFile(int id)
        {
            var result = _fileService.DeleteRestaurentFile(id);

            if (result.IsSuccessful)
                return RedirectToAction("EditRestaurant", "Home", new { Id = result.ParentId });
            else
                return View();
        }

        #endregion

        #region Private 

        private List<SelectListItem> GetCountry()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            var countryList = _restaurantService.CountryList();

            foreach (var item in countryList)
            {
                items.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                });
            }

            return items;
        }

        private List<SelectListItem> GetCategories()
        {
            List<SelectListItem> items = new List<SelectListItem>();

EnterpriseApp.BackOffice/Views/Shared/_Layout.cshtml
@using EnterpriseApp.BackOffice.Filters;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EnterpriseApp BackOffice</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/css/busyindicator.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/css/busyindicator.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EnterpriseApp BackOffice</a>
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage Restaurants <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Restaurant" asp-action="ViewRestaurants">Restaurant</a></li>
                            <li><a asp-area="" asp-controller="RestaurantConfig" asp-action="Index">Configuration</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>

                    @if (Context.IsSignedIn())
                    {
                        <li><a asp-area="" asp-controller="Auth" asp-action="Logout">Logout( @Context.UserName())</a></li>
                    }
                    else
                    {
                        <li>
                            <a asp-controller="Auth" asp-action="Login">Login</a>
                        </li>
                    }


                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="loader overlay">
            <div class="overlay-content">
                <div id="globalBusyIndicator" class="overlay-text">Please wait...</div>
            </div>
        </div>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EnterpriseApp.BackOffice</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/busyindicator.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/busyindicator.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)

    @RenderSection("styles", required: false)
</body>
</html>